name: Test bump2version

on:
  push:
    branches:
      - test

jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build bump2version
          --user

      - name: Set up Git identity
        run: |
          git config --global user.name "chenhuifei01"
          git config --global user.email "chenhui1@uchicago.edu"

      - name: Bump minor version
        run: bump2version patch

      - name: Push
        run: git push --tags
          