name: Cocoa Error Analysis

on:
  push:
    branches:
      - main

jobs:
  cocoa_check:
    runs-on: ubuntu-latest

    environment:
      name: cocoa_standards

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  

    - name: Install cocoa
      run: pip3 install dsi-cocoa  

    - name: Run cocoa and check output
      id: cocoa_run
      run: |
        run_string="cocoa . --lint --verbose "

        if [ ! -z "${{ vars.REVIEW_AFTER_DATE }}" ]; then
            echo "Running cocoa from date: ${{ vars.REVIEW_AFTER_DATE }}"
            run_string+="--date ${{ vars.REVIEW_AFTER_DATE }} "    
        fi

        if [ ! -z "${{ vars.BRANCH_NAME }}" ]; then
            echo "Running cocoa on branch: ${{ vars.BRANCH_NAME }}"
            run_string+="--branch ${{ vars.BRANCH_NAME }} "    
        fi

        output=$($run_string)
        echo "$output"

        if echo "$output" | grep -iq 'Warning'; then
          echo "Warning detected."
        fi

        if echo "$output" | grep -iq 'Error'; then
          echo "Error detected."
          exit 1  
        fi
      shell: bash

    - name: Success
      run: echo "No critical issues found"
