name: Cocoa Error Analysis

on:
  push:
    branches:
      - main
      - ridhi-error-badge

jobs:
  cocoa_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  

    - name: Install cocoa
      run: pip3 install dsi-cocoa  

    - name: Run cocoa and check output
      id: cocoa_run
      run: |
        output=$(cocoa . --lint --verbose)
        echo "$output"
        if echo "$output" | grep -iq 'Warning'; then
          echo "Warning detected."
        fi
        if echo "$output" | grep -iq 'Error'; then
          echo "Error detected."
          exit 1  
        fi
      shell: bash

    - name: Success
      run: echo "No critical issues found"
